<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FindLiteAI.Core\FindLiteAI.Core.csproj" />
    <ProjectReference Include="..\FindLiteAI.Extensions.DependencyInjection\FindLiteAI.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\FindLiteAI\FindLiteAI.csproj" />
  </ItemGroup>

</Project>
