<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FindLiteAI.Core\FindLiteAI.Core.csproj" />
    <ProjectReference Include="..\..\src\FindLiteAI.Extensions.DependencyInjection\FindLiteAI.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\FindLiteAI\FindLiteAI.csproj" />
  </ItemGroup>

</Project>
