<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FindLiteAI.Core\FindLiteAI.Core.csproj" />
    <ProjectReference Include="..\..\src\FindLiteAI.Embeddings.Onnx\FindLiteAI.Embeddings.Onnx.csproj" />
    <ProjectReference Include="..\..\src\FindLiteAI.Extensions.DependencyInjection\FindLiteAI.Extensions.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\FindLiteAI\FindLiteAI.csproj" />
  </ItemGroup>

</Project>
